import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => (
    <div>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <h1>UI Colors</h1>
        <p> Mobile UI and color input in first POC</p>
    </div>
);

export default Home;
